[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
shiba_token = "9MKQUJxTgX4HbetajYfvg69xXU6f1TXiuqezVgQjHa65"

[registry]
url = "https://devnet.helius-rpc.com/?api-key=44b7171f-7de7-4e68-9d08-eff1ef7529bd"

[provider]
cluster = "Devnet"
wallet = "./keys/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/shiba-token.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true
